# Generated by Django 4.1.2 on 2023-01-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_firstname_order_lastname_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
